# Spark Streaming Job Configuration
spark:
  master: "local"
  app_name: "KafkaToIceberg"
  packages:
    - "org.apache.spark:spark-sql-kafka-0-10_2.12:3.4.1"
    - "org.apache.kafka:kafka-clients:3.3.1"
    - "org.apache.spark:spark-avro_2.12:3.4.1"
    - "org.apache.iceberg:iceberg-spark-runtime-3.4_2.12:1.3.1"
    - "org.apache.hadoop:hadoop-aws:3.3.2"
    - "com.amazonaws:aws-java-sdk-bundle:1.12.262"
## spark version 3.4.1 호환 jars

# Schema Registry
schema_registry:
  url: "http://15.165.7.37:8081"
  subject: "userlog-avro-topic-value"

# Kafka
kafka:
  brokers: "15.165.7.37:9092,3.35.6.38:9092,3.38.200.113:9092"
  topic: "userlog-avro-topic"

# Iceberg
iceberg:
  catalog_name: "userlogs_catalog"
  warehouse_path: "s3a://userlog-data/warehouse"
  db_name: "analytics"
  table_name: "user_logs"
  checkpoint_location: "s3a://userlog-data/checkpoints/user_logs_checkpoint"

# S3 Configuration
s3:
  endpoint: "http://54.180.166.228:9000"
  access_key: "${S3_ACCESS_KEY}"
  secret_key: "${S3_SECRET_KEY}"
  s3_region: "ap-northeast-2"
  path_style_access: true
  connection_ssl_enabled: false

# Streaming Configuration
streaming:
  processing_time_trigger: "30 minutes"

# Schema Version State Management
schema_version_state:
  s3_bucket: "userlog-data" # 또는 ${SCHEMA_VERSION_S3_BUCKET}
  s3_key: "schema_versions/userlog-avro-topic-value.version" # 또는 ${SCHEMA_VERSION_S3_KEY}

# Slack (선택 사항)
slack:
  webhook_url: "${SLACK_WEBHOOK_URL}" # 환경 변수 또는 직접 값
